// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYIVkm0IeDoFDmQTNoiMLjEDemG20YNWk',
    appId: '1:650546964342:web:0c12771ae3f501324bbc57',
    messagingSenderId: '650546964342',
    projectId: 'namma-mart-bfd60',
    authDomain: 'namma-mart-bfd60.firebaseapp.com',
    storageBucket: 'namma-mart-bfd60.firebasestorage.app',
    measurementId: 'G-NRCXFE3DWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVfTRKgUVbeQXcRzZIvogxvOJRWNyUzOE',
    appId: '1:650546964342:android:32edc1e08f31b7f44bbc57',
    messagingSenderId: '650546964342',
    projectId: 'namma-mart-bfd60',
    storageBucket: 'namma-mart-bfd60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw2a9FNDlB3K4p8VoZHwgwAxdTz7jo8R0',
    appId: '1:650546964342:ios:4463c69879f5166a4bbc57',
    messagingSenderId: '650546964342',
    projectId: 'namma-mart-bfd60',
    storageBucket: 'namma-mart-bfd60.firebasestorage.app',
    iosBundleId: 'com.example.nammaExpress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw2a9FNDlB3K4p8VoZHwgwAxdTz7jo8R0',
    appId: '1:650546964342:ios:4463c69879f5166a4bbc57',
    messagingSenderId: '650546964342',
    projectId: 'namma-mart-bfd60',
    storageBucket: 'namma-mart-bfd60.firebasestorage.app',
    iosBundleId: 'com.example.nammaExpress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYIVkm0IeDoFDmQTNoiMLjEDemG20YNWk',
    appId: '1:650546964342:web:6d3fd13661de8fd34bbc57',
    messagingSenderId: '650546964342',
    projectId: 'namma-mart-bfd60',
    authDomain: 'namma-mart-bfd60.firebaseapp.com',
    storageBucket: 'namma-mart-bfd60.firebasestorage.app',
    measurementId: 'G-MPQQDEZY5S',
  );
}
